# Docker compose to create the asciidocs from ./docs/*.md and convert them to pdfs in the ./output dir
services:
  asciidoctor:
    build:
      context: .
      dockerfile: tools/asciidoctor/Dockerfile
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./output:${OUTPUT_DIR}
    command: ["/bin/sh", "-c", "${APP_DIR}/00_create_pdfs.sh"]

  md2adoc:
    # Only 'docker compose --profile md2adoc up' will start this service
    profiles:
      - md2adoc
    build:
      context: .
      dockerfile: tools/md2adoc/Dockerfile
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./output:${OUTPUT_DIR}
    command: ["/bin/sh", "-c", "${APP_DIR}/00_convert_docs.sh"]